# Sample Server Configuration File for Grin-Miner
#
# Grin-Miner will look for this file in these places: in the following
# order:
#
# -The working directory
# -The directory in which the executable resides

#########################################
### LOGGING CONFIGURATION             ###
#########################################

[logging]

# Whether to log to stdout
log_to_stdout = true

# Log level for stdout: Critical, Error, Warning, Info, Debug, Trace
stdout_log_level = "Info"

# Whether to log to a file
log_to_file = true

# Log level for file: Critical, Error, Warning, Info, Debug, Trace
file_log_level = "Debug"

# Log file path
log_file_path = "grin-miner.log"

# Whether to append to the log file (true), or replace it on every run (false)
log_file_append = true

#########################################
### MINING CLIENT CONFIGURATION       ###
#########################################

[mining]

# whether to run the tui
run_tui = true

# listening grin stratum server url
stratum_server_addr = "127.0.0.1:13416"

# login for the stratum server (if required)
#stratum_server_login = "http://192.168.1.100:13415"

# password for the stratum server (if required)
#stratum_server_password = "x"

#The directory in which mining plugins are installed
#if not specified, grin miner will look in the directory /deps relative
#to the executable

#miner_plugin_dir = "target/debug/plugins"

# temporary, for testnet 2 compatibility
# t2 or less : set to true (default)
# t3 or greater : set to false
hash_header = false

#########################################
### CUCKOO MINER PLUGIN CONFIGURATION ###
#########################################

# Multiple plugins can be specified, (e.g. a cpu
# miner and a gpu miner running in parallel)

# You'll likely get the best performance using a
# single GPU plugin and single CPU plugin in parallel

# Parameters can be set per-device. On CPU plugins
# you'll likely only be using device 0 (for now),
# but in CUDA plugins the device number corresponds
# to the device ID. (use nvidia-smi to find this)

#The fastest cpu algorithm, but consumes the most memory
#Also requires instructions that aren't available on
#older processors. In this case, use mean_compat_cpu
#instead
#[[mining.miner_plugin_config]]
#type_filter = "mean_cpu"
#[mining.miner_plugin_config.device_parameters.0]
#NUM_THREADS = 1

#As above, but for older processors
[[mining.miner_plugin_config]]
type_filter = "mean_compat_cpu"
[mining.miner_plugin_config.device_parameters.0]
NUM_THREADS = 4

#note lean_cpu currently has a bug which prevents it from
#working with threads > 1

#[[mining.miner_plugin_config]]
#type_filter = "lean_cpu"
#[mining.miner_plugin_config.device_parameters.0]
#NUM_THREADS = 1

#CUDA Miner
#
# Note! 4+ GB GPU cards only!
#   Tweak the MEM_GB parameter according to how much RAM your
#   card has (valid values are 4,5 or 7)
#   Docs: https://github.com/tromp/cuckoo/blob/master/GPU.md
#
#Can currently be used only in Production (30) Mode
#This plugin is not built by default. To build:
#1) Ensure the latest cuda toolkit is installed
#   (nvcc should be in your PATH)
#   Wrong gcc? install gcc-5 g++-5; export CC=`which gcc-5`; # then build
#2) Uncomment the 'build-cuda-plugin' feature
#   in util/Cargo.toml
#
#Parameters can be set per device, as below.
#device 0 is used by default, and all other devices are
#disabled unless explicitly enabled by setting the 'USE_DEVICE'
#param to 1 on each device, as demonstrated below.

#[[mining.miner_plugin_config]]
#type_filter = "cuda"
#[mining.miner_plugin_config.device_parameters.0]
#USE_DEVICE = 0

# Below are advanced optional per-device tweakable params
# Valid options for MEM_GB are 4,5 and 7
#MEM_GB = 7 
#N_TRIMS = 176
#GEN_A_BLOCKS = 4096
#GEN_A_TPB = 256
#GEN_B_TPB = 128
#TRIM_TPB = 512
#TAIL_TPB = 1024
#RECOVER_BLOCKS = 1024
#RECOVER_TPB = 1024

#[mining.miner_plugin_config.device_parameters.1]
#USE_DEVICE = 1

#[mining.miner_plugin_config.device_parameters.2]
#USE_DEVICE = 1
